services:
  proxy:
    image: hegemonies/site-counter:proxy-0.0.1
    container_name: site-counter-proxy
    ports:
      - "8080:8080"
    environment:
      APP_TOKEN: token

  core:
    image: hegemonies/site-counter:core-0.1.1
    container_name: site-counter-proxy
    environment:
      PROXY_TOKEN: token
      PROXY_ADDRESS: proxy
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DATABASE_USERNAME: tester
      DATABASE_PASSWORD: tester
