name: build and push docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: build docker image
        run: ./gradlew bootBI
      - name: rename docker image
        run: docker tag site-counter:0.0.1 hegemonies/site-counter:0.0.1
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: push docker image
        run: docker push site-counter:0.0.1
